name: Generate and commit data to master

on:
  pull_request:
    types:
      - closed

jobs:
  commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
        with:
          token: ${{ secrets.BOT_ACESS_TOKEN }} 

      - name: Merge appchains and generate JSON
        run: node generateJson.js

      - name: setup git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit
        run: |
          git add .
          git commit -m "update data.json"
          git push 
