name: PR checker
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Merge appchains and generate JSON
        run: node generateJson.js
